App: PharmapackRecognition

Mode: Debug
Database: Enrollment

Dirs:
  SourceDir: /fls/pharmapack
  OutputDir: /fls/pharmapack/output

ImageLoading:
  UseDebugFiles: False
  Shuffle: False
  Seed: True
  Fraction: 1

  Filter:
    Mode: Inclusive
    Packageclass: [1]
    Phone: []
    Distinct: []
    Sample: []
    Angle: [100]
    Size: []

  SortBy: [PackageClass, Phone]
  GroupBy: [] #[PackageClass, Distinct]

Output:
  ClearOutputDir: True
  LogLevel: INFO
  Profile: False

Multithreading:
  Used: True
  CPUs: 6

Detection:
  ScaleFactor: 1
  Algorithms: [MSER, MorphologyIteration1, MorphologyIteration2, MajorVoting]

  ApproximationMethodDefault: Hull
  ApproximationMethodsUsed: [Contour, Brect, Rrect, Hull]
  AlignmentMethod: NoAlignment

  Write: [Images, Visualizations, JSON, CSV]

Evaluation:
  Annotation:
    Mask: True
    Regions: True
  Verification:
    Mask: True
    Regions: True
  Metrics: [a]

ExtractReference:
  Used: False
  Write: True
