App: PharmapackRecognition

Mode: Debug
Database: Enrollment

Dirs:
  SourceDir: /fls/pharmapack
  OutputDir: /fls/pharmapack/output

ImageLoading:
  UseDebugFiles: False
  Shuffle: True
  Seed: True
  Fraction: 0.1

  Filter:
    Mode: Inclusive
    PackageClass: []
    Phone: []
    Distinct: []
    Sample: []
    Size: []

  SortBy:
    - PackageClass
    - Phone

Output:
  ClearOutputDir: True
  LogLevel: INFO
  Profile: False

Multithreading:
  Used: False
  CPUs: Auto
  SplitOnChunks: True

Detection:
  ScaleFactor: 1
  Algorithms:
    - MSER
    - MorphologyIteration1
  ApproximationMethod: Rrect
  AlignmentMethod: NoAlignment
  Write:
    - Images
    - Visualizations
    - JSON
    - CSV

Evaluation:
  Mask:
    Used: True
    Aggregate: True
    Write: True
  Regions:
    Used: True
    Aggregate: True
    Write: True
  Metrics:
    - Accuracy
    - IntersectionOverUnion
    - Sensitivity
    - Precision
    - Specificity

ExtractReference:
  Used: False
  Write: True
