App: PharmaPackRecognition

General:
  Seed: 666

  Mode: Debug
  Database: Enrollment

  DirSource: /fls/pharmapack
  DirOutput: /fls/pharmapack/Output
  ClearDirOutput: True

  LogLevel: INFO
  Profile: False

  Multithreading: False
  Threads: Auto

Loading:
  UseDebugFiles: False

  Shuffle: False
  UseSeed: True
  Fraction: 1

  Filter:
    Mode: Inclusive
    Packageclass: [1]
    Phone: []
    Distinct: []
    Sample: []
    Angle: [100]
    Size: []

  SortBy: [PackageClass, Phone]
  GroupBy: [] #[PackageClass, Distinct]

FineGrained:
  Algorithms: [ MSER, MorphologyIteration1 ]

  DescriptorDefault: AKAZE
  DescriptorsUsed: [AKAZE, SIFT, ORB]

Segmentation:
  ScaleFactor: 1

  AlignmentMethod: Reference
  Algorithms: [MSER, MorphologyIteration1] # LineSegmentation, MorphologyIteration2, MajorVoting

  ApproximationMethodDefault: Contour
  ApproximationMethodsUsed: [Contour, Hull]

  Write: [nn] # mask, regions, json, verref

  QualityEstimation:
    Raise: False
    UseGlares: True
    UseBlur: True

  Evaluation:
    Annotation:
      Mask: True
      Regions: True
    Verification:
      Mask: True
      Regions: True
    Metrics: [all]

  ExtractReference:
    Used: False
    Write: True

Hash:
  Algorithms: [MSER, MorphologyIteration1]
  BaseModel: resnet18
  DescriptorLength: 256

  NeighboursAmount: 15
  TopNeighboursAmount: 9
  TopRankedSize: 10

  Storage:
    Redis:
      Complete: 6
      Insert: 8
      Port: 6379
      Host: localhost
    LMDB:
      Path: "/ndata/chaban/lmdb"

  NearPy:
    Length: 128

  LOPQ:
    CoarseClusters: 16
    Subvectors: 16
    SubquantizerClusters: 512

NN:
  Common:
    BatchSize: 128
    Epochs: 10

    LogEveryNSteps: 1
    EvalEveryNEpochs: 1

    FineTuneFrom: None
    WeightDecay: 0.000001
    FP16Precision: False

    Dataset:
      S: 1
      InputShape: (256, 256, 3)
      NumWorkers: 0
      ValidSize: 0.05

  SimCLR:
    BaseModel: resnet50
    OutDim: 512

    Loss:
      Temperature: 0.5
      UseCosineSimilarity: True
