App: PharmapackRecognition

Mode: Debug
Database: Enrollment

Dirs:
  SourceDir: /fls/pharmapack
  OutputDir: /fls/pharmapack/output

ImageLoading:
  UseDebugFiles: False
  Shuffle: False
  Seed: True
  Fraction: 1

  Filter:
    Mode: Inclusive
    PackageClass: []
    Phone: []
    Distinct: []
    Sample: []
    Angle: [360]
    Size: []

  SortBy:
    - PackageClass
    - Phone

  GroupBy:
    - PackageClass
    - Distinct

Output:
  ClearOutputDir: True
  LogLevel: INFO
  Profile: False

Multithreading:
  Used: False
  CPUs: Auto

Detection:
  ScaleFactor: 1
  Algorithms:
    - MSER
    - MorphologyIteration1
    - MorphologyIteration2
    - MajorVoting

  ApproximationMethodDefault: Hull
  ApproximationMethodsUsed: [Brect, Rrect, Hull]
  AlignmentMethod: NoAlignment

  Write:
    - Images
    - Visualizations
    - JSON
    - CSV

Evaluation:
  Mask:
    Used: True
    Aggregate: True
    Write: True
  Regions:
    Used: True
    Aggregate: True
    Write: True
  Metrics: [a]

ExtractReference:
  Used: False
  Write: True
