App: PharmapackRecognition

Mode: Debug
Database: Enrollment

Dirs:
  SourceDir: /fls/pharmapack
  OutputDir: /fls/pharmapack/Output

ImageLoading:
  UseDebugFiles: False
  Shuffle: False
  Seed: True
  Fraction: 1

  Filter:
    Mode: Inclusive
    Packageclass: [1]
    Phone: []
    Distinct: []
    Sample: []
    Angle: [100]
    Size: []

  SortBy: [PackageClass, Phone]
  GroupBy: [] #[PackageClass, Distinct]

Output:
  ClearOutputDir: True
  LogLevel: INFO
  Profile: False

Multithreading:
  Used: False
  Threads: 6

QualityEstimation:
  RaiseErrors: False
  GlaresUsed: True
  BlurUsed: True

AlignmentMethod: NoAlignment

Detection:
  ScaleFactor: 1
  Algorithms: [MSER, MorphologyIteration1, MorphologyIteration2, MajorVoting] # LineSegmentation

  ApproximationMethodDefault: Contour
  ApproximationMethodsUsed: [Contour, Brect, Rrect, Hull]

  Write: [Images, Visualizations, JSON, CSV]

Evaluation:
  Annotation:
    Mask: True
    Regions: True
  Verification:
    Mask: True
    Regions: True
  Metrics: [a]

ExtractReference:
  Used: False
  Write: True

NN:
  Model: "triplet"

  Common:
    BatchSize: 512
    Epochs: 100

    LogEveryNSteps: 25
    EvalEveryNEpochs: 1

    FineTuneFrom: None
    WeightDecay: 10e-6
    FP16Precision: False

    Dataset:
      S: 1
      InputShape: (256, 256, 3)
      NumWorkers: 0
      ValidSize: 0.05

  SimCLR:
    BaseModel: "resnet50"
    OutDim: 512

    Loss:
      Temperature: 0.5
      UseCosineSimilarity: True
