App: PharmapackRecognition

Mode: Debug
Database: Enrollment

Dirs:
  SourceDir: /fls/pharmapack
  OutputDir: /fls/pharmapack/output

ImageLoading:
  Shuffle: True
  Seed: False
  Percentage: 100

  Filter:
    PackageClass: All
    Phone: All
    Distinct: All
    Sample: All
    Size: All
  SortBy:
    - PackageClass
    - Phone

Output:
  ClearOutputDir: True
  LogLevel: INFO
  Profile: False

Multithreading:
  Used: True
  CPUs: Auto
  SplitOnChunks: True

Detection:
  ScaleFactor: 1
  Algorithms:
    - MSER
    - MorphologyIteration1
  ApproximationMethod: Hull
  AlignmentMethod: NoAlignment
  Write:
    - Images
    - Visualizations
    - JSON
    - CSV

Evaluation:
  Mask:
    Used: True
    Aggregate: True
    Write: True
  Regions:
    Used: True
    Aggregate: True
    Write: True
  Metrics:
    - Accuracy
    - IntersectionOverUnion
    - Sensitivity
    - Precision
    - Specificity

ExtractReference:
  Used: True
  Write: True
