App: PharmapackRecognition

Mode: Debug
Database: Enrollment

Dirs:
  SourceDir: /fls/pharmapack
  OutputDir: /fls/pharmapack/Output

ImageLoading:
  UseDebugFiles: False
  Shuffle: False
  Seed: True
  Fraction: 1

  Filter:
    Mode: Inclusive
    Packageclass: [1]
    Phone: []
    Distinct: []
    Sample: []
    Angle: [100]
    Size: []

  SortBy: [PackageClass, Phone]
  GroupBy: [] #[PackageClass, Distinct]

Output:
  ClearOutputDir: True
  LogLevel: INFO
  Profile: False

Multithreading:
  Used: False
  Threads: 6

QualityEstimation:
  RaiseErrors: False
  GlaresUsed: True
  BlurUsed: True

AlignmentMethod: NoAlignment

Detection:
  ScaleFactor: 1
  Algorithms: [MSER, MorphologyIteration1, MorphologyIteration2, MajorVoting] # LineSegmentation

  ApproximationMethodDefault: Contour
  ApproximationMethodsUsed: [Contour, Brect, Rrect, Hull]

  Write: [mask, regions, json, nn, verref]

Evaluation:
  Annotation:
    Mask: True
    Regions: True
  Verification:
    Mask: True
    Regions: True
  Metrics: [a]

ExtractReference:
  Used: False
  Write: True

NN:
  UsedModel: Hash
  SourceDir: /data/500gb/pharmapack/CNNInput

  Common:
    BatchSize: 128
    Epochs: 10

    LogEveryNSteps: 1
    EvalEveryNEpochs: 1

    FineTuneFrom: None
    WeightDecay: 10e-6
    FP16Precision: False

    Dataset:
      S: 1
      InputShape: (256, 256, 3)
      NumWorkers: 0
      ValidSize: 0.05

  Hash:
    Algorithms: [MSER, MI1]
    BaseModels: [resnet18, resnet50, resnet101]
    DescriptorLengths: [256, 512, 1024]

    Storage:
      Redis:
        CompleteDB: 6
        InsertDB: 8
        Port: 6379
        Host: localhost
      LMDB:
        Path: "/ndata/chaban/lmdb"

    NearPy:
      HashLengths: [64, 96, 128, 160, 256]
      Neighbours: [1, 3, 5, 7, 9, 12]

    LOPQ:
      Models:
        - CoarseClusters: 8
          Subvectors: 4
          SubquantizerClusters: 256

  SimCLR:
    BaseModel: ResNet50
    OutDim: 512

    Loss:
      Temperature: 0.5
      UseCosineSimilarity: True
