App: PharmapackRecognition

Mode: Debug
Database: Enrollment

Dirs:
  SourceDir: /fls/pharmapack
  OutputDir: /fls/pharmapack/Output

ImageLoading:
  UseDebugFiles: False
  Shuffle: False
  Seed: True
  Fraction: 1

  Filter:
    Mode: Inclusive
    Packageclass: [1]
    Phone: []
    Distinct: []
    Sample: []
    Angle: [100]
    Size: []

  SortBy: [PackageClass, Phone]
  GroupBy: [] #[PackageClass, Distinct]

Output:
  ClearOutputDir: True
  LogLevel: INFO
  Profile: False

Multithreading:
  Used: False
  CPUs: 6

QualityEstimation:
  RaiseErrors: False
  GlaresUsed: True
  BlurUsed: True

AlignmentMethod: NoAlignment

Detection:
  ScaleFactor: 1
  Algorithms: [MSER, MorphologyIteration1, MorphologyIteration2, MajorVoting] # LineSegmentation

  ApproximationMethodDefault: Hull
  ApproximationMethodsUsed: [Contour, Brect, Rrect, Hull]

  Write: [Images, Visualizations, JSON, CSV]

Evaluation:
  Annotation:
    Mask: True
    Regions: True
  Verification:
    Mask: True
    Regions: True
  Metrics: [a]

ExtractReference:
  Used: False
  Write: True